name: "ogugu"

services:
  redis:
    image: "redis:alpine"
    container_name: ogugu.redis
    restart: always
    ports:
      - 6479:6379
    volumes:
      - redis-data:/var/lib/redis/data

  ogugu.db:
    image: "postgres:16-alpine"
    container_name: ogugu.db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # not yet sure if this is a good approach but who's watching?
  ogugu.test.db:
    image: "postgres:16-alpine"
    container_name: ogugu.test.db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_TEST_USER}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
      POSTGRES_DB: ${DB_TEST_NAME}
    ports:
      - 5442:5432
    volumes:
      - postgrestest-data:/var/lib/postgresqltest/data

volumes:
  postgres-data:
  redis-data:
  postgrestest-data:
