CREATE TABLE IF NOT EXISTS rss (
	id TEXT PRIMARY KEY NOT NULL UNIQUE,
	name TEXT NOT NULL UNIQUE,
	link TEXT NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
