CREATE TABLE IF NOT EXISTS auth(
	id SERIAL PRIMARY KEY,
	user_id TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (user_id) REFERENCES users(id)
	ON DELETE CASCADE
);
