CREATE TABLE IF NOT EXISTS users_rss(
	id TEXT PRIMARY KEY NOT NULL UNIQUE,
	user_id TEXT NOT NULL,
	rss_id TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (rss_id) REFERENCES rss(id) ON DELETE CASCADE
);
