CREATE TABLE IF NOT EXISTS posts (
	id TEXT PRIMARY KEY NOT NULL UNIQUE,
	rss_id TEXT NOT NULL,
	title TEXT NOT NULL,
	description TEXT NOT NULL,
	link TEXT NOT NULL UNIQUE,
	pubdate TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (rss_id) REFERENCES rss(id)
);
